modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="toolsplusplus"
version="1.0.0"
displayName="Tools++"
displayURL="https://github.com/othyn/tools-plus-plus"
credits="TurtyWurty's 1.16 modding tutorial series, I'd be lost upgrading this mod otherwise: https://youtube.com/playlist?list=PLaevjqy3Xufavi5mWXvWnGmwRylL-QZy7"
authors="Othyn"
description='''
Enhances the default tools with a few additional extras, after spicing them up a little first.
'''

[[dependencies.toolsplusplus]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolsplusplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
